### ISSUE TITLE
After update in iOS SDK build with cordova isn't working

### ISSUE THREAD

**Issue by nirmal-mobiquity** [newrelic/newrelic-cordova-plugin#16]
Getting error
` 'Invalid bitcode version (Producer: '1103.0.32.59.0_0' Reader: '1100.0.33.16_0')', using libLTO version 'LLVM version 11.0.0, (clang-1100.0.33.16)' for architecture x86_64`

**Comment by nirmal-mobiquity** [comment]
@Fahmy-Mohammed getting issue from today can you look into it ?

**Comment by sophos7** [comment]
This error is related to the version of Xcode (clang) that was used when building the library vs the one being used to build the project. The library was built with Xcode 11.4.1 (clang-1103.0.32.59). This means it will need to be built on the same version or newer. It looks like the build system is using Xcode 11.3. 

Xcode will need to be updated to use this version of the library.

**Comment by nirmal-mobiquity** [comment]
Ok I don't want to update xcode and want to use it with 11.3 how I can take older branch of it ? I can't see versioning here.

**Comment by sophos7** [comment]
You'll need to download a previous version of the library which can be done from the [New Relic iOS release notes](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/ios-release-notes). Then replace the files in the `newrelic-cordova-plugin/libs/ios/NewRelicAgent.framework/` directory.

**Comment by nirmal-mobiquity** [comment]
ok thanks @sophos7 will try and let you know

**Comment by dijashub** [comment]
@sophos7  this is faces by me and i tried updating to xcode 11.3 and still same issue...

**Comment by sophos7** [comment]
you'd need to update to Xcode 11.4.1 or newer. The other option is to replace the version of the library in the `NewRelicAgent.framework` directory. You might need to go back to version 6.9.0 which is the first to mention being built on Xcode11.

**Comment by dijashub** [comment]
@sophos7 We archive IPA as part of fastlane devops pipeline and do we have command to pull previous version of newrelic framework . Or this is is a manual step ? To replace to previous version??

I could find command to go to previous version.

Thanks for your help.

**Comment by sophos7** [comment]
As someone mentioned earlier, this repo doesn't have other branches for version. You can either fork the repo and replace the `NewRelicAgent.framework` directory or clone and replace the directory locally. Then use the local location when using the `cordova plugin add` command.

**Comment by dijashub** [comment]
@nirmal-mobiquity  Did you get this resolved for you

I do above mentioned step but still it is going to npm registry to fetch and fails as below.
In package.json If i mention local folder repo instead git repo it is not helping.

-------
npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not found : newrelic-cordova-plugin
npm ERR! 404 
npm ERR! 404  'newrelic-cordova-plugin' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/n081459/.npm/_logs/2020-04-24T20_00_48_811Z-debug.log
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code E404
npm ERR! 404 Not found : newrelic-cordova-plugin
npm ERR! 404 
npm ERR! 404  'newrelic-cordova-plugin' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.


@sophos7 


I dont see other option instead of updating to 11.4.1

**Comment by sophos7** [comment]
Not sure why this would be looking in npm when installing from local or another repo with `cordova plugin add`. If you're still seeing a `libLTO version` error, you might need to use an older version of the library.

If you're still having issue, you might want to create a support ticket with New Relic.

**Comment by ndesai-newrelic** [comment]
@sophos7 we are working on to fix this issue.
